### ISSUE TITLE
ATLAddressBarViewController.h not found in Atlas.h

### ISSUE THREAD

**Issue by nishantdongare** [kwkhaw/quick-start-ios-swift#1]
![screen shot 2015-09-19 at 6 44 03 pm](https://cloud.githubusercontent.com/assets/9926475/9976374/b406ba5e-5eff-11e5-83ca-05f09b525e36.png)
![screen shot 2015-09-19 at 6 53 29 pm](https://cloud.githubusercontent.com/assets/9926475/9976377/be74d1e2-5eff-11e5-89e6-b439c9afaca2.png)

**Comment by kwkhaw** [comment]
Hi @nishantdongare , Thanks for reporting the issue and the snapshot.
From the snapshot, I can tell that:
- You are actually trying to compile Layer-Parse-iOS-Swift-Example project, https://github.com/kwkhaw/Layer-Parse-iOS-Swift-Example, but not quick-start-ios-swift. Thus, you actually opened issue in the wrong project. :stuck_out_tongue: 
- You are using Xcode 6.4 (Correct me if I'm wrong). As stated in the readme of Layer-Parse-iOS-Swift-Example repo, now you need to use Xcode 7 instead.

Kindly use Xcode 7 to compile it and open an issue there if you still encounter any error.

**Comment by nishantdongare** [comment]
ohh sorry for posting in wrong project.
Yes i am using XCode 6.4. But can you tell me one thing. What if we have to support iOS SDK 8.0. 
Is there any way.
And here is the copy of pod file. 

platform :ios, '7.0'

target 'Layer-Parse-iOS-Swift-Example' do
  pod 'LayerKit', '~> 0.15.0'
  pod 'Atlas', '~> 1.0.8'
  pod 'Parse', '~> 1.7.5'
  pod 'ParseUI', '~> 1.1.4'
  pod 'SVProgressHUD', '~> 1.1.3'
end

**Comment by kwkhaw** [comment]
@nishantdongare do you mean your app have to support iOS 8?

**Comment by nishantdongare** [comment]
Yes.

**Comment by kwkhaw** [comment]
I see, I think stackoverflow post would help. http://stackoverflow.com/questions/18568572/whats-the-meaning-of-base-sdk-ios-deployment-target-target-and-project-in-xc
